version: '3'

networks:
  web:
    external: true
  internal:
    external: false
    
services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8072:8080"
    labels: 
      - "traefik.frontend.rule=Host:tu_diminio"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - "web"